{
 "title": "Operator dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Good part counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsiv2_i40process_job000001_i40process\nWHERE\n  attrname = 'goodPartCounter' and\n  recvtimets = (select recvtimets from default_service.urn_ngsiv2_i40process_job000001_i40process order by recvtimets desc limit 1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset\nWHERE\n  attrname = 'oee' and\n  recvtimets = (select recvtimets from default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset order by recvtimets desc limit 1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset\nWHERE\n  attrname = 'oeeAvailability' and\n  recvtimets = (select recvtimets from default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset order by recvtimets desc limit 1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset\nWHERE\n  attrname = 'oeePerformance' and\n  recvtimets = (select recvtimets from default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset order by recvtimets desc limit 1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast(recvtimets as bigint) AS \"time\",\n  cast(attrvalue as real) as attrvalue\nFROM default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset\nWHERE\n  attrname = 'oeeQuality' and\n  recvtimets = (select recvtimets from default_service.urn_ngsiv2_i40asset_injectionmouldingmachine1_i40asset order by recvtimets desc limit 1)\nORDER BY 1"
    }
   ]
  }
 ]
}